name: Push Event
on: 
  push:
    branches: 
      - feature
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "This is a push command on all branches"
